server:
  port: 8083

spring:
  application:
    name: Clients Application

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2

  datasource:  
    url: jdbc:h2:mem:clients
    username: clients_user
    password: clients_user
    driver-class-name: org.h2.Driver

  sql:
    init:
      schema-locations:
      - 'classpath:eventuate-init.sql'
      mode: always
      
  h2:
    console:
      enabled: true
      path: /h2-dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8089/realms/accounts/protocol/openid-connect/certs
          
eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092