server:
  port: 8082

spring:
  application:
    name: Accounts View Service Application

  main:
    web-application-type: reactive

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
  graphql:
    schema:
      locations: classpath:graphql/**
      
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_views

    redis:
      host: localhost
      port: 6379
      
eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092

application:
  events:
    consuming:
      account:
        destination: org.example.accounts_service.application.accounts.domain.Account