server:
  port: 8082

spring:
  application:
    name: Accounts View Service Application

  datasource:
    driver-class-name: org.h2.Driver

  main:
    web-application-type: reactive

  graphql:
    schema:
      locations: classpath:graphql/**
      
application:
  events:
    consuming:
      account:
        destination: org.example.accounts_service.application.accounts.domain.Account