spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2

  datasource:  
    url: jdbc:h2:mem:accounts
    username: accounts_user
    password: accounts_user
    driver-class-name: org.h2.Driver

  sql:
    init:
      schema-locations:
      - 'classpath:persistence/dev/eventuate-init.sql'
      mode: always
      
  h2:
    console:
      enabled: true
      path: /h2-dev

application:
  h2:
    tcp-port: ${APPLICATION_H2_TCP_PORT:9090}