server:
  port: 8081

spring:
  application:
    name: Event Publisher Application

  liquibase:
    enabled: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

# eventuate:
#   outbox:
#     id: 1