spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2

  datasource:  
    url: jdbc:h2:mem:items
    username: item_user
    password: item_user
    driver-class-name: org.h2.Driver

  sql:
    init:
      schema-locations:
      - 'classpath:persistence/dev/eventuate-init.sql'

  h2:
    console:
      enabled: true
      path: /h2-dev