spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:  
    url: jdbc:postgresql://localhost:5432/accounts
    username: accounts_user
    password: accounts_user
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:persistence/prod/changelogs/db.changelog-master.yaml