server:
  port: 8081

spring:
  application:
    name: Event Publisher Application

  liquibase:
    enabled: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8089/realms/accounts/protocol/openid-connect/certs
          
management:
  endpoints:
    web:
      exposure:
        include: '*'

# eventuate:
#   outbox:
#     id: 1